version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: recipe-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: recipedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Docker-managed volume
    deploy:
      resources:
        limits:
          memory: 1GB  # Limit PostgreSQL to 1GB RAM
          cpus: "1.0"  # Restrict PostgreSQL to 1 CPU core

volumes:
  pgdata:
    driver: local  # Default Docker volume driver
